# Generated by Django 3.2.9 on 2021-12-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
