# Generated by Django 3.2.9 on 2021-12-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_pistas_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pistas',
            name='imagen',
            field=models.IntegerField(null=True),
        ),
    ]
