# Generated by Django 3.2.9 on 2021-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pistas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pistas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='pistas'),
        ),
    ]
