# Generated by Django 3.2.9 on 2021-12-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
