# Generated by Django 3.2.9 on 2021-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_reservas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='horaf',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='horar',
            field=models.DateField(),
        ),
    ]
