# Generated by Django 3.2.9 on 2022-05-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_reservas_hora1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='horaf',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='horar',
        ),
        migrations.AddField(
            model_name='reservas',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservas',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.club'),
        ),
    ]
