# Generated by Django 3.2.9 on 2022-05-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20220522_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='hora1',
            new_name='hora',
        ),
    ]
