# Generated by Django 3.2.9 on 2022-05-22 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_rename_hora1_reservas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pistas',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.club'),
        ),
    ]
