# Generated by Django 3.2.9 on 2022-05-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_pistas_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pistas',
            name='club',
        ),
    ]
