# Generated by Django 3.2.9 on 2022-05-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_pistas_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='fecha',
            field=models.DateField(),
        ),
    ]
