# Generated by Django 3.2.9 on 2022-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_reservas_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
