# Generated by Django 3.2.9 on 2022-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_club_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='telefono',
            field=models.IntegerField(max_length=9, null=True),
        ),
    ]
