# Generated by Django 3.2.9 on 2022-06-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_club_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[['consulta', 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='hora',
            field=models.IntegerField(choices=[['17:00', '17:00'], ['18:30', '18:30'], ['20:00', '20:00'], ['21:30', '21:30']], null=True),
        ),
    ]
