# Generated by Django 3.2.9 on 2022-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_reservas_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hora',
            name='hora',
        ),
        migrations.AddField(
            model_name='hora',
            name='hora1',
            field=models.TimeField(null=True),
        ),
    ]
