# Generated by Django 3.2.9 on 2022-06-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_auto_20220606_2036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hora',
        ),
    ]
