# Generated by Django 3.2.9 on 2022-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_delete_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.CharField(choices=[['consulta', 'consulta'], ['reclamo', 'reclamo'], ['sugerencia', 'sugerencia'], ['felicitaciones', 'felicitaciones']], max_length=20, null=True),
        ),
    ]
