# Generated by Django 3.2.9 on 2022-06-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_hora_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='club',
        ),
    ]
