# Generated by Django 3.2.9 on 2022-06-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_remove_reservas_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hora',
            name='club',
        ),
        migrations.RemoveField(
            model_name='pistas',
            name='club',
        ),
    ]
