# Generated by Django 3.2.9 on 2022-11-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_auto_20220619_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='hora',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.club'),
        ),
        migrations.AddField(
            model_name='pistas',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.club'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.club'),
        ),
    ]
